# -*- coding: utf-8 -*-
"""actividad principal python.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C4AWy8ASgg1iTuJ01TM2uabDNdN85QYQ
"""

print ("hola mundo!!!")

"""variable

TALLER NUMERO 1, CON COMPLEMENTO DE LA SECCION 4 DE SENTENCIAS CONDICIONALES Y APLICACION DEL TALLER # 2.
"""

, os
nombre = input("digite su nombre")
print(nombre)
apellidos = "cardenas mendieta"
print(apellidos)
tipodeidentificacion = "cedula"
print(tipodeidentificacion)
#cedula de ciudadania colombiana
numerodeidentificacion = 1109068822
print(numerodeidentificacion)
direccion = "carrera 16b # 42c 60 sur"
print(direccion)
barrio = "moralba"
print(barrio)
ciudad = "Bogota"
print(ciudad) 
telefono = 3008301694
#variable que almacena el numero de una persona
print(telefono)
#variable que muestra en pantalla el numero de telefono personal
edad = "35 años"
print(edad)
estadocivil = "soltero"
print(estadocivil)
numerodehijos = 1
if numerodehijos > 0:
  print("tiene al menos un hijo aplica para el paseo") 
#variable que gestiona informacion sobre su rol como padre
estaturaencm = 1,75 
print(estaturaencm)
oficio= "auxiliar administrativo"
salario = 2000000
if salario >= 1000000:
 print("si la variable salario es igual o menor a 1000000 aplica para bono alimenticio")
print(f"salario:${salario}")
print(oficio)
experiencia = "auxiliar administrativo en soluciones operativas sas, durante 7 años"
print(experiencia)
#las descripciones hechas en esta variable estan sujetas a soporte con la debida documentacion
diaslab = 120
if diaslab >= 20:
  print ("trabajo mas de 20 dias al mes por tiempo laborado aplica para bono alimenticio")
print(diaslab)

edad = int(input("cuantos años tiene?"))
if edad > 55:
  print("es usted mayor de 55.")
else:
  print("es usted menor de 55 no cumple condicion para bono de prepension.")