# -*- coding: utf-8 -*-
"""ejercicios de operaciones matematicas python.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qfi8yW4-g4S2_cM2KCgROZMQ6ZjVsvoI

#**OPERADORES MATEMÁTICOS EN PTYHON**
"""

num1 = 5
num2 = 4
res = num1 + num2
print(res)

# por default la función INPUT() - STR
num1 = int(input("Digite el número 1: "))
num2 = int(input("Digite el número 2: "))
resultado = num1 + num2
print("La suma de {} y {} es = {}".format(num1, num2, resultado ))

"""**CALCULADORA** + - * /"""

num1 = int(input("Digite el número 1: "))
num2 = int(input("Digite el número 2: "))

suma = num1 + num2
resta = num1 - num2
multi = num1 * num2
divi = num1 / num2

print("\nEl resultado de la SUMA es= {}".format(suma))
print(f"\nEl resultado de la SUMA es= {suma}")
print("\nEl resultado de la RESTA es= {}".format(resta))
print("\nEl resultado de la MULTIPLICACIÓN es= {}".format(multi))
print(f"\nEl resultado de la DIVISIÓN es= {divi}")

"""Se recibe una venta por concepto de un prodcuto se requiere aplicar el IVA (19%) y conocer el total a pagar con el IVA Incluido"""

# variable para capturar la venta
venta = float(input("¿Cuánto fue el total de la compra? "))
# cálculo del IVA
iva = venta * 0.19
# Suma el IVa con la venta
total = venta + iva
# Visualiza el total a pagar por pantalla
print("El IVA es = {:,.0f} y el total a pagar es = {:,.0f}".format(iva, total))
print(f"El IVA es = {iva:,.0f} y el total a pagar es = {total:,.0f}")

"""Se requiere conocer el promerdio general de una materia que está dada por tres calificaciones"""

cal1 = float(input("Digite la calificaicón 1: "))
cal2 = float(input("Digite la calificaicón 2: "))
cal3 = float(input("Digite la calificaicón 3: "))

prom = round((cal1 + cal2 + cal3 ) /3, 2)

print(f"El promedio es= {prom}")

"""# **Taller Refuerzo**
https://drive.google.com/file/d/1jFH9DgCRha_dn9JG7c_jjTpeE5x5kK3d/view?usp=sharing

EJERCICIOS DE REFUERZO OPERACIONES MATEMATICAS.
"""

# variable para determinar suelto total
sueldo  = float(input("¿cuanto es el sueldo total?"))
# calculo de comisiones
comision = sueldo  * 0.10
# suma el sueldo b con la comision
total= sueldo  + comision
# visualiza el total a pagar por pantalla
print("la comision es = {:,.0f} y el total a pagar es = {:,.0f}". format(comision, total) )

precio = float(input("digite el precio"))

descuento = precio * 0.15
precio  = precio - descuento
print(f"el precio final es ${precio:.2f}")